version: "3"

services:
  sinthorn:
    container_name: sinthorn
    image: panotza/sinthorn:latest
    environment:
      CHANNEL_ACCESS_TOKEN: ''
      CHANNEL_SECRET: ''
      NOTIFY_LINE_ACCOUNT: '[]'
    volumes:
       - './db/:/usr/src/app/db/'
    restart: unless-stopped