version: "3"

services:
  sinthorn:
    container_name: sinthorn
    image: panotza/sinthorn:latest
    environment:
      CHANNEL_ACCESS_TOKEN: ''
      CHANNEL_SECRET: ''
      # line accounts will be notified ex. ["abc","def"]
      NOTIFY_LINE_ACCOUNT: '[]'
      INTERVAL: '30000'
    volumes:
       - './db/:/usr/src/app/db/'
    restart: unless-stopped